### ISSUE TITLE
`options` must be list

### ISSUE THREAD

**Issue by setzler** [setzler/r-tutorial#4]
In Quiz1_ArjG.R, it must be TRUE that class(options)=="list". Currently, class(options)=="character".

**Comment by arjungecon** [comment]
I have fixed it in the .R file.

**Comment by setzler** [comment]
This is clearly not fixed as of commit #7. Here is a screenshot:

<img width="697" alt="options_not_list" src="https://user-images.githubusercontent.com/4136420/43599712-22ab18c8-964e-11e8-9570-156ebc7b18f1.png">

**Comment by arjungecon** [comment]
Sorry for the error - I have updated the file, and sent you a new pull request.
